name: Deploy to Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Deployment
        run: |
          echo "Prod deployment triggered"
          echo "This will call shared workflows actions repo "
          